import { EventEmitter, OnDestroy, OnInit } from '@angular/core';
import { TabDirective } from './tab.directive';
import { TabsetConfig } from './tabset.config';
import { RippleDirective } from './ripple-effect.component';
export declare class TabsetComponent implements OnDestroy, OnInit {
    ripple: RippleDirective;
    tabs: TabDirective[];
    classMap: any;
    protected isDestroyed: boolean;
    protected _vertical: boolean;
    protected _justified: boolean;
    protected _type: string;
    listGetClass: String;
    tabsGetClass: String;
    clazz: boolean;
    buttonClass: String;
    contentClass: String;
    tabEl: any;
    showBsTab: EventEmitter<any>;
    shownBsTab: EventEmitter<any>;
    hideBsTab: EventEmitter<any>;
    hiddenBsTab: EventEmitter<any>;
    vertical: boolean;
    setActiveTab(index: number): void;
    justified: boolean;
    type: string;
    constructor(config: TabsetConfig, ripple: RippleDirective);
    click(event: any, index: any): void;
    ngOnDestroy(): void;
    getActive(): number;
    addTab(tab: TabDirective): void;
    removeTab(tab: TabDirective): void;
    protected getClosestTabIndex(index: number): number;
    protected hasAvailableTabs(index: number): boolean;
    protected setClassMap(): void;
    listGet(): void;
    tabsGet(): void;
    ngOnInit(): void;
}
